/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module \74155  (
  input Ea1,
  input Ea2,
  input A0,
  input A1,
  input Eb1,
  input Eb2,
  output Q0a,
  output Q1a,
  output Q2a,
  output Q3a,
  output Q0b,
  output Q1b,
  output Q2b,
  output Q3b
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s0 = ~ A1;
  assign s2 = ~ A0;
  assign s3 = (~ Ea2 & ~ (~ Ea1));
  assign s5 = (~ Eb2 & ~ Eb1);
  assign s1 = ~ s0;
  assign Q0a = ~ (s0 & s2 & s3);
  assign Q0b = ~ (s0 & s2 & s5);
  assign s4 = ~ s2;
  assign Q1a = ~ (s0 & s4 & s3);
  assign Q2a = ~ (s1 & s2 & s3);
  assign Q3a = ~ (s1 & s4 & s3);
  assign Q1b = ~ (s0 & s4 & s5);
  assign Q2b = ~ (s1 & s2 & s5);
  assign Q3b = ~ (s1 & s4 & s5);
endmodule

module bus_decode (
  input \~{IORQ} ,
  input \~{M1} ,
  input \~{RD} ,
  input \~{WR} ,
  input \~{MREQ} ,
  input PWR_OK,
  input \~{BUSACK} ,
  input VCC,
  input GND,
  input NC_1,
  input \~{RESET0} ,
  input NC_11,
  output \~{INTA} ,
  output \~{IOR} ,
  output \~{IOW} ,
  output \~{MEMR} ,
  output \~{MEMW} ,
  output BUSACK,
  output \~{DBUS_DIR} ,
  output \~{RESET} 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire \~{INTA}_temp ;
  wire \~{RESET}_temp ;
  assign s0 = (\~{M1}  | \~{IORQ} );
  assign BUSACK = ~ \~{BUSACK} ;
  assign \~{RESET}_temp  = (PWR_OK & \~{RESET0} );
  assign s1 = ~ s0;
  assign s2 = (\~{WR}  & \~{RESET}_temp );
  assign s3 = ~ s2;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( s1 ),
    .D( 1'b0 ),
    .C( 1'b0 ),
    .Clr( s3 ),
    .Q( s4 ),
    .\~Q ( s5 )
  );
  assign s6 = (s5 | (~ s0 & ~ s2));
  \74155  \74155_i1 (
    .Ea1( s6 ),
    .Ea2( \~{IORQ}  ),
    .A0( \~{WR}  ),
    .A1( \~{RD}  ),
    .Eb1( \~{MREQ}  ),
    .Eb2( s4 ),
    .Q1a( \~{IOR}  ),
    .Q2a( \~{IOW}  ),
    .Q1b( \~{MEMR}  ),
    .Q2b( \~{MEMW}  )
  );
  assign \~{INTA}_temp  = (s0 & (s6 | \~{RD} ));
  assign \~{DBUS_DIR}  = (\~{MREQ}  & \~{INTA}_temp );
  assign \~{INTA}  = \~{INTA}_temp ;
  assign \~{RESET}  = \~{RESET}_temp ;
endmodule
