/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module chip_selects (
  input \~{M1} ,
  input \~{MREQ} ,
  input \~{IORQ} ,
  input \~{RESET} ,
  input [15:0] A, // Address bus.
  output RESET,
  output \~{PPI_CS} ,
  output \~{UART_CS} ,
  output \~{HI_ADDR} 
);
  wire a_5;
  wire a_2;
  wire a_3;
  wire a_4;
  wire a_6;
  wire [7:0] s0;
  wire \~{io_op} ;
  wire \~{mem_op} ;
  wire \~{a_4} ;
  wire \~{a_2} ;
  wire \~{a_6} ;
  wire \~{a_7} ;
  wire hi_addr;
  assign RESET = ~ \~{RESET} ;
  assign \~{io_op}  = (\~{IORQ}  | ~ \~{M1}  | ~ \~{MREQ} );
  assign \~{mem_op}  = (~ \~{IORQ}  | \~{MREQ} );
  assign \~{a_7}  = ~ A[7];
  assign a_2 = A[2];
  assign a_3 = A[3];
  assign a_4 = A[4];
  assign a_5 = A[5];
  assign a_6 = A[6];
  assign s0 = A[15:8];
  assign \~{a_4}  = ~ a_4;
  assign \~{a_2}  = ~ a_2;
  assign \~{a_6}  = ~ a_6;
  assign hi_addr = (s0[0] | s0[1] | s0[2] | s0[3] | s0[4] | s0[5] | s0[6] | s0[7]);
  assign \~{PPI_CS}  = (a_2 | ~ a_3 | a_4 | ~ a_5 | a_6 | \~{a_7}  | hi_addr | \~{io_op} );
  assign \~{HI_ADDR}  = ~ hi_addr;
  assign \~{UART_CS}  = (a_3 | a_4 | a_5 | a_6 | \~{a_7}  | hi_addr | \~{io_op} );
endmodule
