/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

// 8-line to 3-Line priority encoder
module \74148  (
  input EI,
  input \0 ,
  input \1 ,
  input \2 ,
  input \3 ,
  input \4 ,
  input \5 ,
  input \6 ,
  input \7 ,
  input VCC,
  input GND,
  output A2,
  output A1,
  output A0,
  output GS,
  output E0
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign A2 = ((\4  & \5  & \6  & \7 ) | EI);
  assign GS = ((\0  & \1  & \2  & \3  & \4  & \5  & \6  & \7 ) | EI);
  assign s2 = ~ \2 ;
  assign s0 = ~ \4 ;
  assign s1 = ~ \5 ;
  assign s3 = ~ \6 ;
  assign A1 = ((\2  & \3  & \6  & \7 ) | (s0 & \6  & \7 ) | (s1 & \6  & \7 ) | EI);
  assign A0 = ((\1  & \3  & \5  & \7 ) | (s2 & \3  & \5  & \7 ) | (s0 & \5  & \7 ) | (s3 & \7 ) | EI);
  assign E0 = (~ \0  | ~ \1  | s2 | ~ \3  | s0 | s1 | s3 | ~ \7  | EI);
endmodule

module Driver
(
    input in,
    input sel,
    output out
);
    assign out = (sel == 1'b1)? in : 1'bz;
endmodule
