/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module mem_req (
  input \~{B_RFSH} ,
  input \~{B_MREQ} ,
  output \~{MEM_REQ} 
);
  assign \~{MEM_REQ}  = (\~{B_MREQ}  | ~ \~{B_RFSH} );
endmodule
