/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module ppi_chip_select (
  input A_7,
  input A_6,
  input A_5,
  input A_4,
  input A_3,
  input \~{B_IORQ} ,
  input \~{B_M1} ,
  output \~{PPI_CS} 
);
  assign \~{PPI_CS}  = (~ A_3 | A_4 | ~ A_5 | A_6 | ~ A_7 | \~{B_IORQ}  | ~ \~{B_M1} );
endmodule
