/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module ppi_slot_select (
  input [7:0] \~{CSLH} ,
  input \~{SLTSL_CS} ,
  input A14,
  input A15,
  input \~{MEM_REQ} ,
  output \~{SLTSL_0} ,
  output \~{SLTSL_1} ,
  output \~{SLTSL_2} ,
  output \~{SLTSL_3} 
);
  wire s0;
  wire s1;
  wire \~{CSLH}_0 ;
  wire \~{CSLH}_1 ;
  wire \~{CSLH}_2 ;
  wire \~{CSLH}_3 ;
  wire \~{CSLH}_4 ;
  wire \~{CSLH}_5 ;
  wire \~{CSLH}_6 ;
  wire \~{CSLH}_7 ;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  assign s0 = ~ A14;
  assign s1 = ~ A15;
  assign \~{CSLH}_0  = \~{CSLH} [0];
  assign \~{CSLH}_1  = \~{CSLH} [1];
  assign \~{CSLH}_2  = \~{CSLH} [2];
  assign \~{CSLH}_3  = \~{CSLH} [3];
  assign \~{CSLH}_4  = \~{CSLH} [4];
  assign \~{CSLH}_5  = \~{CSLH} [5];
  assign \~{CSLH}_6  = \~{CSLH} [6];
  assign \~{CSLH}_7  = \~{CSLH} [7];
  assign \~{SLTSL_0}  = ((s0 & s1 & \~{CSLH}_0  & ~ \~{SLTSL_CS} ) | (s0 & s1 & \~{CSLH}_1  & ~ \~{SLTSL_CS} ) | (A14 & s1 & \~{CSLH}_2  & ~ \~{SLTSL_CS} ) | (A14 & s1 & \~{CSLH}_3  & ~ \~{SLTSL_CS} ) | (s0 & A15 & \~{CSLH}_4  & ~ \~{SLTSL_CS} ) | (s0 & A15 & \~{CSLH}_5  & ~ \~{SLTSL_CS} ) | (A14 & A15 & \~{CSLH}_6  & ~ \~{SLTSL_CS} ) | (A14 & A15 & \~{CSLH}_7  & ~ \~{SLTSL_CS} ) | \~{MEM_REQ} );
  assign s9 = ~ \~{CSLH}_7 ;
  assign s5 = ~ \~{CSLH}_6 ;
  assign s8 = ~ \~{CSLH}_5 ;
  assign s4 = ~ \~{CSLH}_4 ;
  assign s7 = ~ \~{CSLH}_3 ;
  assign s3 = ~ \~{CSLH}_2 ;
  assign s6 = ~ \~{CSLH}_1 ;
  assign s2 = ~ \~{CSLH}_0 ;
  assign \~{SLTSL_1}  = ((s0 & s1 & s2) | (s0 & s1 & \~{CSLH}_1 ) | (A14 & s1 & s3) | (A14 & s1 & \~{CSLH}_3 ) | (s0 & A15 & s4) | (s0 & A15 & \~{CSLH}_5 ) | (A14 & A15 & s5) | (A14 & A15 & \~{CSLH}_7 ) | \~{MEM_REQ}  | \~{SLTSL_CS} );
  assign \~{SLTSL_2}  = ((s0 & s1 & \~{CSLH}_0 ) | (s0 & s1 & s6) | (A14 & s1 & \~{CSLH}_2 ) | (A14 & s1 & s7) | (s0 & A15 & \~{CSLH}_4 ) | (s0 & A15 & s8) | (A14 & A15 & \~{CSLH}_6 ) | (A14 & A15 & s9) | \~{MEM_REQ}  | \~{SLTSL_CS} );
  assign \~{SLTSL_3}  = ((s0 & s1 & s2) | (s0 & s1 & s6) | (A14 & s1 & s3) | (A14 & s1 & s7) | (s0 & A15 & s4) | (s0 & A15 & s8) | (A14 & A15 & s5) | (A14 & A15 & s9) | \~{MEM_REQ}  | \~{SLTSL_CS} );
endmodule
